name: ui-unit

on:
    push:
    pull_request:

jobs:
    unit:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [16]

        steps:
            - name: Checkout
              uses: actions/checkout@master
              with:
                  submodules: 'recursive'

            - name: Setup node env
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: ${{ matrix.node }}

            - name: Install dependencies
              run: npm i

            - name: Install test dependencies
              run: npm ci --workspace ui

            - name: Run production build
              run: npm run build --workspace ui

            - name: Run unit tests
              run: npm run test --workspace ui
